# Generated by Django 5.0.6 on 2026-06-13 21:51

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_accent_color_remove_user_density_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
