# Generated by Django 5.2.15 on 2026-06-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='departmentmember',
            name='deptmember_dept_head_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobtitle',
            name='jobtitle_workspace_level_idx',
        ),
        migrations.RemoveIndex(
            model_name='orgprofile',
            name='orgprofile_jobtitle_idx',
        ),
        migrations.RemoveIndex(
            model_name='teammember',
            name='teammember_team_lead_idx',
        ),
        migrations.RemoveField(
            model_name='departmentmember',
            name='is_head',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='is_lead',
        ),
        migrations.AddField(
            model_name='orgprofile',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contractor', 'Contractor'), ('intern', 'Intern')], default='full_time', max_length=20),
        ),
    ]
