# Generated by Django 5.0.6 on 2026-06-19 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='projects.taskcomment'),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
