# Generated by Django 5.2.15 on 2026-06-22 03:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_taskcomment_parent_taskstatus_is_started'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_board_status_idx',
        ),
        migrations.AddField(
            model_name='board',
            name='key',
            field=models.CharField(blank=True, db_index=True, max_length=6),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['board', 'status', 'order'], name='task_board_status_order_idx'),
        ),
    ]
