# Generated by Django 5.0.6 on 2026-06-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_taskattachment_taskdependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('task', 'Task'), ('bug', 'Bug'), ('feature', 'Feature'), ('story', 'Story'), ('improvement', 'Improvement'), ('question', 'Question')], default='task', max_length=20),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
