# Generated by Django 5.0.6 on 2026-06-08 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_importjob_report_reportshare_scheduledreport_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
