# Generated by Django 5.0.6 on 2026-06-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_delete_dashboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportJob',
        ),
    ]
