# Generated by Django 5.0.6 on 2026-06-09 21:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_webhook_webhookdelivery_workspaceapikey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('jira', 'Jira'), ('clickup', 'ClickUp'), ('monday', 'Monday'), ('notion', 'Notion'), ('github', 'GitHub Issues'), ('asana', 'Asana'), ('csv', 'Simple CSV')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('mapped', 'Mapping Ready'), ('importing', 'Importing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('parsed_rows', models.JSONField(default=list)),
                ('field_mapping', models.JSONField(default=dict)),
                ('preview_rows', models.JSONField(default=list)),
                ('progress_pct', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('imported_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('error_log', models.JSONField(default=list)),
                ('imported_task_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
