# Generated by Django 5.0.6 on 2026-06-13 21:51

import core.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_delete_notificationpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importjob',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='inboxitem',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='webhook',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='webhookdelivery',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='workspaceapikey',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='slug',
        ),
        migrations.AlterField(
            model_name='importjob',
            name='id',
            field=core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='id',
            field=core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='id',
            field=core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='id',
            field=core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='id',
            field=core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workspaceapikey',
            name='id',
            field=core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workspaceinvite',
            name='id',
            field=core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='id',
            field=core.fields.UUIDv7Field(default=core.fields.generate_uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['workspace', 'status'], name='importjob_workspace_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inboxitem',
            index=models.Index(fields=['user', 'status'], name='inbox_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inboxitem',
            index=models.Index(fields=['user', 'workspace', 'status'], name='inbox_user_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read'], name='notif_recipient_read_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'created_at'], name='notif_recipient_created_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['webhook', 'created_at'], name='webhookdel_webhook_created_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['webhook', 'success'], name='webhookdel_webhook_success_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceinvite',
            index=models.Index(fields=['workspace', 'status'], name='wsinvite_workspace_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemember',
            index=models.Index(fields=['workspace', 'role'], name='wsmember_workspace_role_idx'),
        ),
    ]
