# Generated by Django 5.0.6 on 2026-06-19 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0011_remove_inboxitem_notification_alter_inboxitem_verb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inboxitem',
            old_name='project_id',
            new_name='board_id',
        ),
    ]
